### ISSUE TITLE
Create main page layout

### ISSUE THREAD

**Issue by zeeberry** [Category-Colors/category-colors#19]
# Purpose of this work
To build out the foundational layout of the MVP.

# Acceptance Criteria
- [ ] When a user loads up the home page (http://localhost:3000) they see a barebones version of the MVP (see design below)
- [ ] Use Chakra UI components for the text and layout

# Designs
![Image](https://github.com/Category-Colors/category-colors/assets/2035194/2bcf8ff4-a083-40ff-8fb3-ea219899e1b5)

# Notes
[Here's the link to the Figma file](https://www.figma.com/file/V35D6fnk78MsU34omCf8Hn/Chakra-UI-Figma-Kit-(Community)?type=design&node-id=2203-2936&mode=design&t=gPzv7WtWtet90L97-0) so you can inspect the colors and other details

**Comment by r1g023** [comment]
@zeeberry - I have completed the task according to the design above (screenshot). I submitted a few PRs so please let me know if I missed anything or if you need me to do anything else please.
