### ISSUE TITLE
Code in subdirectory

### ISSUE THREAD

**Issue by ilikescience** [Category-Colors/category-colors#2]
Should we put the code in the main directory or leave it in a subdirectory? I'm not sure what the recommended directory structure is for next.js projects 🤔

**Comment by zeeberry** [comment]
@ilikescience I'll take a look

**Comment by zeeberry** [comment]
@ilikescience the approach in #1 (extra subdirectory) was a result of following the nextjs instructions. I moved everything a directory up in #8. I think it's a lot cleaner that way. Nice call bringing it up!
