### ISSUE TITLE
Add Prettier

### ISSUE THREAD

**Issue by zeeberry** [Category-Colors/category-colors#24]
# Purpose of this work
To an opinionated code formatter so that all the code that gets pushed follows the same format and is consistent. 

# Acceptance Criteria
- [ ] Add pre-commit hook so prettier runs on commit. 
- [ ] Formats all current files
- [ ] Add instructions for setup

# Notes
Check here for more info: https://prettier.io/docs/en/index.html

**Comment by ilikescience** [comment]
lgtm! I love prettier :)
